USE [master]
GO

/****** Object:  Database [Grocery]    Script Date: 10/22/2012 14:54:11 ******/
CREATE DATABASE [Grocery] ON  PRIMARY 
( NAME = N'Grocery', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLSNEWSOM\MSSQL\DATA\Grocery.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Grocery_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLSNEWSOM\MSSQL\DATA\Grocery_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Grocery] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Grocery].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Grocery] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Grocery] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Grocery] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Grocery] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Grocery] SET ARITHABORT OFF 
GO

ALTER DATABASE [Grocery] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Grocery] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Grocery] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Grocery] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Grocery] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Grocery] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Grocery] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Grocery] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Grocery] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Grocery] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Grocery] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Grocery] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Grocery] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Grocery] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Grocery] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Grocery] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Grocery] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Grocery] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Grocery] SET  READ_WRITE 
GO

ALTER DATABASE [Grocery] SET RECOVERY FULL 
GO

ALTER DATABASE [Grocery] SET  MULTI_USER 
GO

ALTER DATABASE [Grocery] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Grocery] SET DB_CHAINING OFF 
GO

